name: CD - Deploy Backend to Azure VM

on:
  workflow_run:
    workflows: ["CI Pipeline Backend"]
    types:
      - completed

jobs:

  create_env_file:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.status == 'completed' }}
    runs-on: ubuntu-latest

    steps:
      - name: Create .env on Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/azureuser/myapp

            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

            echo "Archivo .env actualizado en el servidor."

  deploy_app:
    needs: create_env_file  
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/azureuser/myapp

            echo "Haciendo pull de la nueva imagen..."
            docker-compose pull

            echo "Recreando contenedores..."
            docker-compose up -d --remove-orphans

            echo "Contenedores actualizados:"
            docker ps -a
