name: CI Pipeline Backend

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: fastapi_project
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Upload venv and project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-env
          path: fastapi_project

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download environment artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-env
          path: fastapi_project

      - name: Run unit tests
        working-directory: fastapi_project
        run: |
          source venv/bin/activate
          pytest tests/unit --html=report_unit.html

      - name: Upload unit test report
        uses: actions/upload-artifact@v4
        with:
          name: report-unit
          path: fastapi_project/report_unit.html

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Download environment artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-env
          path: fastapi_project

      - name: Run integration tests
        working-directory: fastapi_project
        run: |
          source venv/bin/activate
          pytest tests/integration --html=report_integration.html

      - name: Upload integration test report
        uses: actions/upload-artifact@v4
        with:
          name: report-integration
          path: fastapi_project/report_integration.html

  test_report:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Download unit report
        uses: actions/download-artifact@v4
        with:
          name: report-unit
          path: reports

      - name: Download integration report
        uses: actions/download-artifact@v4
        with:
          name: report-integration
          path: reports

      - name: Send reports to Telegram
        run: |
          curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
               -F document=@reports/report-unit.html \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument

          curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
               -F document=@reports/report_integration.html \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument

  docker_build_and_publish:
    runs-on: ubuntu-latest
    needs: test_report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version TAG
        id: vars
        run: echo "TAG=v1.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: fastapi_project
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-backend:${{ env.TAG }}
            ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
