name: CI Pipeline Backend

on:
  push:
    branches: [main]

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    outputs:
      unit_status: ${{ steps.set-status.outputs.unit_status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('fastapi_project/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        working-directory: fastapi_project
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Cache pytest
        uses: actions/cache@v3
        with:
          path: ~/.cache/pytest
          key: pytest-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            pytest-${{ runner.os }}-

      - name: Run unit tests
        id: unit
        working-directory: fastapi_project
        continue-on-error: true
        run: |
          source .venv/bin/activate
          pytest test/test_unit --html=report_unit.html --tb=short

      - name: Set unit test status
        id: set-status
        run: |
          if [ "${{ steps.unit.outcome }}" = "success" ]; then
            echo "unit_status=passed" >> $GITHUB_OUTPUT
          else
            echo "unit_status=failed" >> $GITHUB_OUTPUT
          fi

      - name: Upload unit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-unit
          path: fastapi_project/report_unit.html
          if-no-files-found: warn

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    if: needs.unit_tests.outputs.unit_status == 'passed'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('fastapi_project/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        working-directory: fastapi_project
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Cache pytest
        uses: actions/cache@v3
        with:
          path: ~/.cache/pytest
          key: pytest-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            pytest-${{ runner.os }}-

      - name: Run integration tests
        working-directory: fastapi_project
        continue-on-error: true
        run: |
          source .venv/bin/activate
          pytest test/test_integration --html=report_integration.html --tb=short

      - name: Upload integration report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-integration
          path: fastapi_project/report_integration.html
          if-no-files-found: warn

  test_report:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    if: always()

    steps:

      - name: Download unit report
        uses: actions/download-artifact@v4
        with:
          name: report-unit
          path: reports

      - name: Try download integration report
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: report-integration
          path: reports

      - name: Send reports to Telegram
        run: |
          curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
               -F document=@reports/report_unit.html \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument || true

          if [ -f reports/report_integration.html ]; then
            curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                 -F document=@reports/report_integration.html \
                 https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument || true
          fi


  docker_build:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests, test_report]
    if: |
      needs.unit_tests.outputs.unit_status == 'passed' &&
      needs.integration_tests.result == 'success'

    outputs:
      docker_tag: ${{ steps.export_tag.outputs.docker_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate version TAG
        id: export_tag
        run: |
          TAG=v1.${GITHUB_RUN_NUMBER}
          echo "docker_tag=$TAG" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Container/Backend/Dockerfile
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: my-backend:${{ steps.export_tag.outputs.docker_tag }}

      - name: Save Docker image as artifact
        run: |
          mkdir -p /tmp/docker-image
          docker save my-backend:${{ steps.export_tag.outputs.docker_tag }} -o /tmp/docker-image/backend-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image/backend-image.tar
          retention-days: 1

  docker_publish:
    runs-on: ubuntu-latest
    needs: docker_build
    if: always()  # Solo depende del resultado de docker_build, no de los tests

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image

      - name: Load Docker image
        run: |
          docker load -i /tmp/docker-image/backend-image.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          TAG=${{ needs.docker_build.outputs.docker_tag }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

          docker tag my-backend:$TAG $DOCKER_USERNAME/my-backend:$TAG
          docker push $DOCKER_USERNAME/my-backend:$TAG
          
          docker tag my-backend:$TAG $DOCKER_USERNAME/my-backend:latest
          docker push $DOCKER_USERNAME/my-backend:latest

  